In [1]:
import numpy as np

li = [1,2,3,4,5]
a =np.random.randint(1,20,5)
b = np.random.randint(1,20,5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[11  6 19 11  2]
[15  1 17  2 12]


In [3]:
 li = [i+1 for i in li]
 a =a+1
 b=b+1
 li
 a
 b

array([17,  3, 19,  4, 14])

In [4]:
c = a + b
c

array([30, 11, 40, 17, 18])

In [6]:
d =  a-b
d

array([ -4,   5,   2,   9, -10])

In [8]:
h = a ** b
h

array([1645991757,        512,  547383789,      28561,  268435456],
      dtype=int32)