In [41]:
import numpy as np

li = [1,2,3,4,5]
a =np.random.randint(1,20,5)
b = np.random.randint(1,20,5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[ 6  7 15  6  6]
[13 13 11  2  8]


In [42]:
 li = [i+1 for i in li]
 a =a+1
 b=b+1
 li
 a
 b

array([14, 14, 12,  3,  9])

In [43]:
c = a + b
c

array([21, 22, 28, 10, 16])

In [44]:
d =  a-b
d

array([-7, -6,  4,  4, -2])

In [45]:
h = a ** b
h

array([-381759919,          0,          0,        343,   40353607],
      dtype=int32)

In [46]:
# Boolean indexing 
import numpy as np 
a = np.array(['t','a','c','b','d','r','t','r'])
b = np.random.randint(1,20,8)
print(a)
print(b)



['t' 'a' 'c' 'b' 'd' 'r' 't' 'r']
[11 18 11  3 12  1  3  9]


In [47]:
print(b>10)

[ True  True  True False  True False False False]


In [48]:
bool_array = b>10
# We are getting only those value in the array whose value is true
new_arr = b[bool_array]
print(new_arr)

[11 18 11 12]


In [49]:
new_arr = b[(b>10) & (b<18)]
print(new_arr)

[11 11 12]


In [50]:
# print(b)
# c =b
# c

In [51]:
print(c)
c[:3] = 19
print(c)
c[c > 15] = 100
print(c)



[21 22 28 10 16]
[19 19 19 10 16]
[100 100 100  10 100]


In [52]:
# where() function is used to find the index of any no in the array
ind = np.where(b == 100)
ind


(array([], dtype=int64),)

In [53]:
print(b)

[11 18 11  3 12  1  3  9]


In [54]:
ind = np.where(b==100)
print(ind)

(array([], dtype=int64),)


In [55]:
# Question-1
arr = [1,2,0,0,4,0]
arr1 = np.array(arr)
print(arr1)
ind1 = np.where(arr1 != 0)
ind1


[1 2 0 0 4 0]


(array([0, 1, 4], dtype=int64),)

In [60]:
# Question-2
array = [1,3,5,7,9,11,13,15,17,19]
array1 = np.array(array)
index2 = np.where(array1 % 3 == 0)
index2

(array([1, 4, 7], dtype=int64),)

In [64]:
array2 = [1,2,3,4,5,6,7,8,9,10]
array3 = np.array(array2)
index3 = np.where(array3 % 2 != 0)
index3

array3[index3] = -1
print(array3)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [66]:
# Broadcasting
# ímport numpy as np
# IF size of 2D array are not same then the broadcasting come
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3,3))

print(x)
print(y)



[[2 7 5]
 [1 5 8]
 [7 8 9]]
[[4 5 2]
 [1 4 2]
 [9 7 5]]


In [67]:
ans = x - y
ans

array([[-2,  2,  3],
       [ 0,  1,  6],
       [-2,  1,  4]])

In [68]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3))

print(x)
print(y)

[[9 9 3]
 [5 4 5]
 [2 2 6]]
[7 5 4]


In [69]:
ans = x - y
ans

array([[ 2,  4, -1],
       [-2, -1,  1],
       [-5, -3,  2]])

In [70]:
x = np.random.randint(1,10,(3,2))
y = np.random.randint(1,10,(2,3))

print(x)
print(y)

[[6 1]
 [7 4]
 [8 4]]
[[7 6 3]
 [3 9 2]]


In [73]:
y =np.transpose(y)
ans = x -y 
ans

array([[-1, -2],
       [ 1, -5],
       [ 5,  2]])