In [2]:
# Numpy is Numerical Python, all kind of packages depend heavily
# Numpy array is much faster

In [3]:
import numpy as np

In [4]:
a = [1,2,3,4]
b = np.array(a)
print(b)
print(type(b))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
a = [1,2,3,'5','a',4.5]
b = np.array(a,dtype = str)
print(b)

['1' '2' '3' '5' 'a' '4.5']


In [6]:
# Repeat array three times
a = [1,2,3,'5',4.5]
b = np.array(a * 3)
print(b)

['1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5']


In [7]:
b = np.ones(3,dtype=int)
b

array([1, 1, 1])

In [9]:
b = np.zeros(3,dtype=int)
b

array([0, 0, 0])

In [12]:
b = np.zeros((3,4),dtype = int)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
np.full((5,6),3,dtype=float)

array([[3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.]])

In [20]:
a = np.empty(4,dtype=int)
print(a);

[1 2 3 4]


In [22]:
a = [[1,2,3],[4,5,6],[7,8,9]]
numpyarray = np.array(a)
print(numpyarray)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
a = np.zeros(10,dtype = int)
a[4] = 1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [29]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
b = np.arange(2,20,2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
b = np.linspace(2,10)
b
print(b[1] - b[0])

0.16326530612244916


In [35]:
b =np.linspace(2,10,5,dtype = int)
b

array([ 2,  4,  6,  8, 10])

In [38]:
b =np.linspace(2,10,5,dtype = int, endpoint=False)
b

array([2, 3, 5, 6, 8])

In [39]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [44]:
b = np.random.rand(3)
b

array([0.58950888, 0.81638975, 0.27165626])

In [45]:
b = np.random.rand(2,3)
b

array([[0.50918185, 0.88446748, 0.19679261],
       [0.00365271, 0.42214244, 0.92632279]])

In [47]:
np.random.rand(10)*10

array([3.36359958, 5.43225298, 6.79732366, 8.72598453, 6.90078241,
       8.52812305, 7.09031773, 6.16904529, 6.41665081, 4.07876047])

In [48]:
b = np.random.rand(3)
b

array([0.29655334, 0.26288467, 0.73090654])

In [51]:
x = np.array([1, 2, 3, 4,5,5,7])
x.shape

(7,)

In [1]:
import numpy as np 
li = [1,2,3,4,5]

arr = np.array(li)

print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [2]:
print(arr.data)

In [3]:
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int32
(4,)


In [5]:
  li_2d = [[1,2,3,4],[4,5,6,7],[8,9,10,11],[12,13,14,15]]
  arr_2d = np.array(li_2d)

  print(li_2d)
  print(arr_2d)

[[1, 2, 3, 4], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [6]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(4, 4)
int32
(16, 4)


In [7]:
  # accesing elements from the numpy array
print(li[3])
print(arr[3])


4
4


In [8]:
# similar slicing of array
print(li[1:4])
print(arr[1:4])

[2, 3, 4]
[2 3 4]


In [11]:
print(arr_2d[2][1])
print(arr_2d[2,1])

9
9


In [12]:
print(li_2d[1][:3])
print(arr_2d[1,:3])

[4, 5, 6]
[4 5 6]


In [15]:
print(arr_2d[0:3,2])

[ 3  6 10]
